name: 🪴New Breeding Program
description: I would like to update the breeding program map.
title: "[PROGRAM]: "
labels: "program"

body:
  - type: dropdown
    id: state
    attributes:
      label: State
      description: |
        Select the state where the breeding program is located.
      options:
        - Alabama
        - Alaska
        - Arizona
        - Arkansas
        - California
        - Colorado
        - Connecticut
        - Delaware
        - Florida
        - Georgia
        - Hawaii
        - Idaho
        - Illinois
        - Indiana
        - Iowa
        - Kansas
        - Kentucky
        - Louisiana
        - Maine
        - Maryland
        - Massachusetts
        - Michigan
        - Minnesota
        - Mississippi
        - Missouri
        - Montana
        - Nebraska
        - Nevada
        - New Hampshire
        - New Jersey
        - New Mexico
        - New York
        - North Carolina
        - North Dakota
        - Ohio
        - Oklahoma
        - Oregon
        - Pennsylvania
        - Rhode Island
        - South Carolina
        - South Dakota
        - Tennessee
        - Texas
        - Utah
        - Vermont
        - Virginia
        - Washington
        - West Virginia
        - Wisconsin
        - Wyoming
        - Puerto Rico
        - Other
    validations:
      required: true

  - type: input
    id: crop_general
    attributes:
      label: Crop
      description: |
        Enter the general crop type for the breeding program.
      placeholder: Crop
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Name
      description: Enter the breeder's name.
      placeholder: Name
    validations:
      required: true

  - type: input
    id: organization
    attributes:
      label: Organization
      description: Enter the organization associated with the breeding program.
      placeholder: Organization
    validations:
      required: true